version: '2'
services:

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - pool-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd1
      MYSQL_DATABASE: pool
      MYSQL_USER: user1
      MYSQL_PASSWORD: userpwd1
      MYSQL_ROOT_HOST: '%'

  pool-server:
    build: .
    ports:
      - "8082:8082"

volumes:
  pool-data: